### ISSUE TITLE
What licence is available on GB1900.ORG place name data?

### ISSUE THREAD

**Issue by Addaci** [Maphackathon/data-sets#24]

**Comment by Addaci** [comment]
EM from Professor Humphrey Southwood to Colin Greenstreet, 07/02/2017:

Dear Colin,

This is just to assure you that we will have a GB1900 dump online pretty soon. Paula needs to sort out the zip file, and has been pretty busy the last couple of weeks, but that work is pretty much done and the preparation won’t take long.

The only restriction we are placing on the dump is that people can create what they like from it but they can’t call what they create the "GB1900 Gazetteer” — i.e. the restriction is on use of the name, not the data.

Obviously, this is because we want there to be a single reasonably definitive version of the gazetteer, but that does not mean that will be created solely or even mainly by ourselves, and we are very interested in collaboration and maybe even forms of competition. I actually think that two distinct datasets need to be created, one that is simply cleaned up, the other being a subset limited to “place names” (which raises an issue of definitions).

Best wishes,

Humphrey
Humphrey Southall
Professor of Historical Geography/
Director, GB Historical GIS
University of Portsmouth
Geography Dept, Buckingham Bldg,
Lion Terrace, Portsmouth PO1 3HE, UK
Humphrey.Southall@port.ac.uk

**Comment by Addaci** [comment]
EM from Colin Greenstreet to Professor Humphrey Southwood, 07/02/2017

Thank Humphrey. Fully understand the restrictions on use of GB1900 name. We are going to use name tag as the branding with full acknowledgement and links to all data providers. We are working with Professor Matthew Davies to see if we can get access to the MOLA concordance between Morgan (1682) and Richie (1746) place names and will be group creating further place name data from various maps and from data mining. Are there any further physical and 
/ or digital gazetteers you can point us to which we can look at and potentially integrate and enrich in our name tag hack?

Best wishes, Colin Greenstreet

**Comment by michaelstoner** [comment]
The license is CC0 https://creativecommons.org/share-your-work/public-domain/cc0/ and a link to the specific file https://github.com/Maphackathon/data-sets/blob/master/gb1900rawData/CC0_LICENCE_GB1900_Raw_Gazetteer_Data_Dump.txt

**Comment by michaelstoner** [comment]
CC0 means you can do what ever you want with it, we only ask:

> 
> Acknowledgments are welcome. Please reference this dataset as the "GB1900 raw gazetteer data dump" made available by the GB1900 Project.
> Please DO NOT refer to this dataset as the GB1900 gazetteer.
